 /*
  * Copyright 2012 Michael Bischoff
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
  * You may obtain a copy of the License at
  *
  *   http://www.apache.org/licenses/LICENSE-2.0
  *
  * Unless required by applicable law or agreed to in writing, software
  * distributed under the License is distributed on an "AS IS" BASIS,
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  */

package de.jpaw.bonaparte.dsl.generator.ts

import de.jpaw.bonaparte.dsl.BonScriptPreferences
import de.jpaw.bonaparte.dsl.bonScript.ClassDefinition
import de.jpaw.bonaparte.dsl.bonScript.ClassReference
import de.jpaw.bonaparte.dsl.bonScript.EnumDefinition
import de.jpaw.bonaparte.dsl.bonScript.FieldDefinition
import de.jpaw.bonaparte.dsl.bonScript.XEnumDefinition
import de.jpaw.bonaparte.dsl.generator.DataTypeExtension
import de.jpaw.bonaparte.dsl.generator.java.JavaEnum
import java.util.LinkedHashMap
import java.util.Map
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext

import static extension de.jpaw.bonaparte.dsl.generator.XUtil.*

/** Generator which produces TypeScript type definitions (one file per class / enum / xenum).
 * It is only called if enabled in the preferences (-Dbonaparte.TypeScript=true).
 *
 * Wire-format rules (verified against a live bonaparte server):
 * - Plain (non-alpha) enums are serialized as numeric ordinals
 * - Alpha enums are serialized as their token strings
 * - `instant` is serialized as epoch seconds (number)
 * - `day`, `time`, `timestamp` are serialized as strings
 * - `enumset` (numeric index) is serialized as an integer bitmap
 * - `xenumset` is serialized as a string
 * - Every object carries a `'@PQON'` field with the partially qualified object name
 * - List elements may be null (fixed-size lists contain nulls)
 * - Plain `Object` / `Element` map to `BonaPortable`
 */
class TypeScriptBonScriptGeneratorMain extends AbstractGenerator {
    public static final String GENERATED_TS_SUBFOLDER = "resources/ts/"
// cannot start with a slash, must end with a slash
    public static final String GENERATED_COMMENT = "// autogenerated by bonaparte DSL. Do not modify, changes will be lost."

    override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext unused) {
        if (TsModuleResolver.isCurrentModule(resource)) {
            val modules = resource.resourceSet.resources.filter[
                TsModuleResolver.isCurrentModule(it) || TsModuleResolver.isIncludedModule(it)].toList
            for (source : modules) {
                for (e : source.allContents.toIterable.filter(typeof(EnumDefinition)))
                    fsa.generateFile(e.tsFilename(e.name), e.writeEnum)
                for (e : source.allContents.toIterable.filter(typeof(XEnumDefinition)))
                    fsa.generateFile(e.tsFilename(e.name), e.writeXEnum)
                for (c : source.allContents.toIterable.filter(typeof(ClassDefinition)))
                    fsa.generateFile(c.tsFilename(c.name), c.writeInterface)
                val folder = TsModuleResolver.outputFolder(source)
                fsa.generateFile(folder + "package.json", entryPointPackageJson)
                fsa.generateFile(folder + "ng-package.json", entryPointNgPackageJson)
                fsa.generateFile(folder + "index.ts", writeModuleIndex(modules, source))
                fsa.generateFile(folder + "api-index.ts", GENERATED_COMMENT + "\nexport {};\n")
            }
        }
    }

    def private static CharSequence entryPointPackageJson() {
        '''{
          "ngPackage": {
            "lib": {
              "entryFile": "index.ts"
            }
          }
        }
        '''
    }

        def private static CharSequence entryPointNgPackageJson() {
                '''{
                    "$schema": "../node_modules/ng-packagr/ng-package.schema.json",
                    "lib": {
                        "entryFile": "index.ts"
                    }
                }
                '''
        }

    def private static CharSequence writeModuleIndex(Iterable<Resource> resources, Resource module) {
        val out = new StringBuilder
        val exportedNames = new java.util.LinkedHashSet<String>
        out.append(GENERATED_COMMENT).append("\n\n")
        for (source : resources.filter[TsModuleResolver.isSameModule(it, module)]) {
            for (e : source.allContents.toIterable.filter(typeof(EnumDefinition))) {
                if (exportedNames.add(e.name))
                    out.append("export { ").append(e.name).append(" } from './")
                        .append(e.packagePath).append("/").append(e.name).append("';\n")
            }
            for (e : source.allContents.toIterable.filter(typeof(XEnumDefinition))) {
                if (exportedNames.add(e.name))
                    out.append("export type { ").append(e.name).append(" } from './")
                        .append(e.packagePath).append("/").append(e.name).append("';\n")
            }
            for (c : source.allContents.toIterable.filter(typeof(ClassDefinition))) {
                if (exportedNames.add(c.name)) {
                    val modulePath = "./" + c.packagePath + "/" + c.name
                    out.append("export { ").append(c.name).append("PQON } from '").append(modulePath).append("';\n")
                    out.append("export type { ").append(c.name).append(" } from '").append(modulePath).append("';\n")
                    if (c.extendsClass !== null && c.extendsClass.classRef !== null
                            && !TsModuleResolver.isSameModule(c, c.extendsClass.classRef))
                        out.append("export { is").append(c.name).append(" } from '").append(modulePath).append("';\n")
                }
            }
        }
        out.append("export * from './api-index';\n")
        out
    }

    def private static String packagePath(EObject d) {
        d.package.name.replace('.', '/')
    }

    def private static String bonaPortablePath(String packageName) {
        val npmPackage = BonScriptPreferences.getTsNpmPackage
        if (npmPackage !== null && !npmPackage.blank)
            return npmPackage
        val path = new StringBuilder
        for (i : 0 ..< packageName.split("\\.").length)
            path.append("../")
        path.append("../rpc-core/bona-portable")
        path.toString
    }

    def private static String tsFilename(EObject d, String name) {
        TsModuleResolver.outputFolder(d.eResource) + d.packagePath + "/" + name + ".ts"
    }

    /** Relative module specifier to import type "name" of the package of "target" into a file of the package of "from". */
    def private static String importPath(EObject from, EObject target, String name) {
        val crossModulePath = TsModuleResolver.crossModuleImport(from, target)
        if (crossModulePath !== null)
            return crossModulePath
        val fromParts = from.package.name.split("\\.")
        val toParts = target.package.name.split("\\.")
        var common = 0
        while (common < fromParts.length && common < toParts.length && fromParts.get(common) == toParts.get(common))
            common++
        val buff = new StringBuilder
        if (common == fromParts.length)
            buff.append("./")
        else
            for (i : common ..< fromParts.length)
                buff.append("../")
        for (i : common ..< toParts.length)
            buff.append(toParts.get(i)).append("/")
        buff.append(name)
        return buff.toString
    }

    def private static CharSequence writeImports(EObject from, Map<String, EObject> refs) {
        val out = new StringBuilder
        for (r : refs.entrySet) {
            if (from !== r.value)
                out.append("import type { ").append(r.key).append(" } from \"")
                    .append(importPath(from, r.value, r.key)).append("\";\n")
        }
        out
    }

    def private static CharSequence jsdoc(String text) {
        if (text === null)
            return ""
        // strip the comment delimiters of the bonaparte javadoc comment
        val body = text.replaceFirst("^/\\*\\*", "").replaceFirst("\\*/$", "").trim
        return '''
            /** «body.replace("*/", "* /")» */
        '''
    }

    /** Deprecated marker for classes, enums, fields, packages. */
    def private static CharSequence deprecatedMarker(EObject d) {
        val isDep = if (d instanceof ClassDefinition) d.isDeprecated
                    else if (d instanceof EnumDefinition) d.isDeprecated
                    else if (d instanceof XEnumDefinition) d.isDeprecated
                    else if (d instanceof FieldDefinition) d.isDeprecated
                    else false
        if (isDep)
            return "/** @deprecated */\n"
        return ""
    }

    def private static CharSequence writeEnum(EnumDefinition d) {
        val alpha = JavaEnum.isAlphaEnum(d)
        '''
            «GENERATED_COMMENT»

            «d.javadoc.jsdoc»
            «d.deprecatedMarker»
            «IF alpha»
                export const «d.name» = {
                    «FOR v : d.avalues SEPARATOR ","»
                        «v.name»: "«v.token»"
                    «ENDFOR»
                } as const;
                export type «d.name» = (typeof «d.name»)[keyof typeof «d.name»];
            «ELSE»
                export const «d.name» = {
                    «FOR v : d.values SEPARATOR ","»
                        «v»: «d.values.indexOf(v)»
                    «ENDFOR»
                } as const;
                export type «d.name» = (typeof «d.name»)[keyof typeof «d.name»];
            «ENDIF»
        '''
    }

    def private static CharSequence writeXEnum(XEnumDefinition d) {
        '''
            «GENERATED_COMMENT»

            «d.javadoc.jsdoc»
            «d.deprecatedMarker»
            export type «d.name» = string;
        '''
    }

    def private static CharSequence writeInterface(ClassDefinition d) {
        val refs = new LinkedHashMap<String, EObject>
        val generics = if (!d.genericParameters.empty) '''<«FOR g : d.genericParameters SEPARATOR ", "»«g.name» = unknown«ENDFOR»>'''
        val parent = if (d.extendsClass !== null)
            " extends Omit<" + d.extendsClass.tsClassRef(d, refs) + ", '@PQON'>"
        val guard = d.typeGuard
        val pqon = d.package.name + "." + d.name
        val body = '''
            «FOR f : d.fields»
                «f.javadoc.jsdoc»
                «f.deprecatedMarker»
                «f.name»«IF !f.cannotBeNull»?«ENDIF»: «f.tsFieldType(d, refs)»;
            «ENDFOR»
            '@PQON': typeof «d.name»PQON;
        '''
        return '''
            «GENERATED_COMMENT»
            import type { BonaPortable } from "«bonaPortablePath(d.package.name)»";
            «d.writeImports(refs)»

            export const «d.name»PQON = "«pqon»" as const;
            «d.javadoc.jsdoc»
            «d.deprecatedMarker»
            export interface «d.name»«generics»«parent» {
                «body»
            }
            «guard»
        '''
    }

    def private static CharSequence typeGuard(ClassDefinition d) {
        val parent = d.extendsClass
        if (parent === null || parent.plainObject || parent.classRef === null
                || TsModuleResolver.isSameModule(d, parent.classRef))
            return ""
        return TsModuleResolver.typeGuard(d.name, d.package.name + "." + d.name)
    }

    /** Type of a field, including aggregate and null handling. */
    def private static String tsFieldType(FieldDefinition f, ClassDefinition owner, Map<String, EObject> refs) {
        val base = f.datatype.tsBaseType(owner, refs)
        val isCollection = f.isArray !== null || f.isList !== null || f.isSet !== null
        // list elements may be null (fixed-size lists contain nulls);
        // an optional scalar field may contain null at runtime
        val elem = if (isCollection) base + " | null"
                   else if (!f.cannotBeNull && f.isAggregateScalar) base + " | null" else base
        if (isCollection)
            return (if (elem.contains(" ")) "(" + elem + ")" else elem) + "[]"
        if (f.isMap !== null)
            return "Record<string, " + elem + ">"
        return elem
    }

    // optional scalar fields are "T | null" (a missing field is expressed by the "?")
    def private static boolean isAggregateScalar(FieldDefinition f) {
        f.isArray === null && f.isList === null && f.isSet === null && f.isMap === null
    }

    def private static String tsClassRef(ClassReference r, EObject from, Map<String, EObject> refs) {
        if (r.plainObject)
            return "BonaPortable"
        if (r.genericsParameterRef !== null)
            return r.genericsParameterRef.name
        val cls = r.classRef
        if (cls === null)
            return "BonaPortable"
        refs.put(cls.name, cls)
        if (r.classRefGenericParms.empty)
            return cls.name
        return cls.name + "<" + r.classRefGenericParms.map[tsClassRef(from, refs)].join(", ") + ">"
    }

    /** Maps the (typedef resolved) data type of a field to a TypeScript type, collecting the types to be imported. */
    def private static String tsBaseType(de.jpaw.bonaparte.dsl.bonScript.DataType dt, ClassDefinition owner, Map<String, EObject> refs) {
        val ref = DataTypeExtension.get(dt)
        if (ref.genericsRef !== null)
            return ref.genericsRef.tsClassRef(owner, refs)
        if (ref.objectDataType !== null) {
            refs.put(ref.objectDataType.name, ref.objectDataType)
            return ref.objectDataType.name
        }
        val elem = ref.elementaryDataType
        if (elem === null)
            return "BonaPortable"
        if (elem.enumType !== null) {
            refs.put(elem.enumType.name, elem.enumType)
            return elem.enumType.name
        }
        if (elem.xenumType !== null) {
            refs.put(elem.xenumType.name, elem.xenumType)
            return elem.xenumType.name
        }
        if (elem.enumsetType !== null) {
            // string index type -> string, numeric index type (or default) -> integer bitmap
            val idx = elem.enumsetType.indexType
            if (idx !== null && idx.toLowerCase.startsWith("s"))
                return "string"
            return "number"
        }
        if (elem.xenumsetType !== null) {
            return "string"
        }
        switch (elem.name.toLowerCase) {
            case "boolean":
                "boolean"
            case "byte", case "short", case "int", case "integer", case "long",
            case "float", case "double", case "decimal", case "number", case "fixedpoint":
                "number"
            case "char", case "character", case "uuid", case "day",
            case "ascii", case "unicode", case "uppercase", case "lowercase",
            case "timestamp", case "time",
            case "raw", case "binary":
                "string"
            case "instant":
                "number"
            case "json":
                "Record<string, unknown>"
            case "array":
                "unknown[]"
            case "object", case "element":
                "BonaPortable"
            default:
                "BonaPortable"
        }
    }
}
