# Build and publish package when release is created.

name: Publish Release

run-name: Publish Release ${{ inputs.release_version }}

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        type: string

env:
  JAVA_VERSION_TO_USE: '17'
  JAVA_DISTRI_TO_USE: 'corretto'
  DEPLOY_RETRY: 5

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }})
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Build
      run: mvn -B -U -T 1C package

    - name: Configure Git User
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Release Packages
      run: mvn -B -P github -DretryFailedDeploymentCount=${{ env.DEPLOY_RETRY }} -DreleaseVersion=${{ inputs.release_version }} release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ github.token }}
