# Build and publish package when release is created.

name: Publish Release

run-name: Publish Release ${{ inputs.release_version }}

on:
  workflow_dispatch: # enable manual trigger
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        type: string

env:
  JAVA_VERSION_TO_USE: '11'
  JAVA_DISTRI_TO_USE: 'corretto'
  DEPLOY_RETRY: 5

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }})
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Configure Git User
      run: git config user.name "Release Management"

    - name: Release Packages
      run: mvn -B -U -P github -DretryFailedDeploymentCount=${{ env.DEPLOY_RETRY }} release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Attach plugin zip as artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: de.jpaw.updatesite.zip
        path: de.jpaw.updatesite/target/*.zip
