# Build and publish package when release is created.

name: Publish Release

on:
  release:
    types: [created]

env:
  JAVA_VERSION_TO_USE: '11'
  JAVA_DISTRI_TO_USE: 'corretto'
  DEPLOY_RETRY: 10

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }})
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Remove SNAPSHOT from version
      run: mvn -B versions:set -DremoveSnapshot

    - name: Update eclipse metadata
      run: mvn -B org.eclipse.tycho:tycho-versions-plugin:update-eclipse-metadata
      
    - name: Build with Maven
      run: mvn -B package

    - name: Build and Publish
      run: mvn -B -Pgithub -DdeployAtEnd=true -DretryFailedDeploymentCount=${{ env.DEPLOY_RETRY }} deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
