# Build and publish snapshot package when pushed to master

name: Publish Snapshot

on:
  workflow_dispatch: # enable manual trigger
  push:
    branches: [ "master" ]
    paths-ignore: [ ".github/**" ]

# cancel already running instances of this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  JAVA_VERSION_TO_USE: '17'
  JAVA_DISTRI_TO_USE: 'corretto'
  DEPLOY_RETRY: 5

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }})
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ secrets.GH_WORKFLOWS_MAVEN_VERSION }}

    - name: Build and Publish
      run: mvn -B -U -P github -DretryFailedDeploymentCount=${{ env.DEPLOY_RETRY }} deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
